### ISSUE TITLE
Check Video Duration with YouTube API

### ISSUE THREAD

**Issue by SaintPeter** [SaintPeter/RoboPlay-Scoreboard-2#7]
Videos must be at least 1 minute long and no longer than 5 minutes.  Enforce this with the YouTube API when validating the video.

Possibly store the video length in the DB, for future reference.

**Comment by duck132912** [comment]
try clicking [here](https://stackoverflow.com/questions/18920336/how-to-get-video-duration-using-youtube-api/18921555) for some info

**Comment by SaintPeter** [comment]
Haha, thanks @duck132912.  I've implemented this in the latest version, just have not been maintaining my issues well.
